export const photos = [
    { id: 1, title: "The Beach", subtitle: "Wonderful waves", content: `
        # Hello, world!
        `, likes: 3, image: "/blog-img.jpg", uploadedAt: "7/5/2024", time: "12:33", tags:["Beach"] },

    { id: 2, title: "Spring Time", subtitle: "A lot of wonderful memories", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit id fugit, voluptatibus, obcaecati neque ducimus maiores omnis explicabo deleniti laudantium voluptatum repudiandae quia similique iusto eius aut reiciendis quidem voluptates doloremque sed. Quaerat consectetur, illo ea velit ipsam itaque veritatis officia animi? Soluta, quas incidunt dignissimos possimus non eos necessitatibus?", likes: 10, image: "/blog-img2.jpg", uploadedAt: "7/5/2024", time: "12:33", tags:["Spring"] },

    { id: 3, title: "Flowers", subtitle: "Tell me about your favorite flower", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit id fugit, voluptatibus, obcaecati neque ducimus maiores omnis explicabo deleniti laudantium voluptatum repudiandae quia similique iusto eius aut reiciendis quidem voluptates doloremque sed. Quaerat consectetur, illo ea velit ipsam itaque veritatis officia animi? Soluta, quas incidunt dignissimos possimus non eos necessitatibus?", likes: 23, uploadedAt: "7/5/2024", time: "12:33", image: "/blog-img3.jpg", tags:["Flowers"] },

    { id: 4, title: "Flowers2", subtitle: "Tell me about your favorite flower again", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit id fugit, voluptatibus, obcaecati neque ducimus maiores omnis explicabo deleniti laudantium voluptatum repudiandae quia similique iusto eius aut reiciendis quidem voluptates doloremque sed. Quaerat consectetur, illo ea velit ipsam itaque veritatis officia animi? Soluta, quas incidunt dignissimos possimus non eos necessitatibus?", likes: 23, uploadedAt: "7/5/2024", time: "12:33", image: "/blog-img3.jpg", tags:["Flowers"] },

    { id: 5, title: "Beachh2", subtitle: "Another wonderful Beach", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit id fugit, voluptatibus, obcaecati neque ducimus maiores omnis explicabo deleniti laudantium voluptatum repudiandae quia similique iusto eius aut reiciendis quidem voluptates doloremque sed. Quaerat consectetur, illo ea velit ipsam itaque veritatis officia animi? Soluta, quas incidunt dignissimos possimus non eos necessitatibus?", likes: 23, uploadedAt: "7/5/2024", time: "12:33", image: "/blog-img3.jpg", tags:["Outside", "Beach"] },
    
    { id: 5, title: "Beachh2", subtitle: "Another wonderful Beach", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit id fugit, voluptatibus, obcaecati neque ducimus maiores omnis explicabo deleniti laudantium voluptatum repudiandae quia similique iusto eius aut reiciendis quidem voluptates doloremque sed. Quaerat consectetur, illo ea velit ipsam itaque veritatis officia animi? Soluta, quas incidunt dignissimos possimus non eos necessitatibus?", likes: 23, uploadedAt: "7/5/2024", time: "12:33", image: "/blog-img3.jpg", tags:["Outside", "Beach"] },
]

export const journal = [
    { id: 1, title: "Took a big step", subtitle: "It was so refreshing outside, and I could see the beauty of the world. I wanted to be outside forever", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit id fugit, voluptatibus, obcaecati neque ducimus maiores omnis explicabo deleniti laudantium voluptatum repudiandae quia similique iusto eius aut reiciendis quidem voluptates doloremque sed. Quaerat consectetur, illo ea velit ipsam itaque veritatis officia animi? Soluta, quas incidunt dignissimos possimus non eos necessitatibus?", likes: 10, image: "/the-sunset.jpg", uploadedAt: "7/5/2024", time: "12:33", tags:["Sky", "Clouds"] },

    { id: 2, title: "It was beautiful", subtitle: "This was my journey to a place. I was hesitant at first, but I really loved the look of the sunset from the car", content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit id fugit, voluptatibus, obcaecati neque ducimus maiores omnis explicabo deleniti laudantium voluptatum repudiandae quia similique iusto eius aut reiciendis quidem voluptates doloremque sed. Quaerat consectetur, illo ea velit ipsam itaque veritatis officia animi? Soluta, quas incidunt dignissimos possimus non eos necessitatibus?", likes: 23, uploadedAt: "7/5/2024", time: "12:33", image: "/travelling.jpg", tags: ["Nature, Outside"] },
]